# Generated by Django 4.0.3 on 2022-03-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=200)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprintParam.parameter')),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprintParam.sprint')),
                ('vote_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_by', to=settings.AUTH_USER_MODEL)),
                ('vote_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_for', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
